"""users and events tables added promoter name 

Revision ID: 43c7e3e8cf12
Revises: 176d8894f939
Create Date: 2019-10-26 14:15:03.344946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c7e3e8cf12'
down_revision = '176d8894f939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('promoter_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_event_promoter_name'), 'event', ['promoter_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_promoter_name'), table_name='event')
    op.drop_column('event', 'promoter_name')
    # ### end Alembic commands ###
