"""cleaning field added to event table 

Revision ID: 44cc83ece10d
Revises: 43c7e3e8cf12
Create Date: 2019-10-27 19:12:51.951103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cc83ece10d'
down_revision = '43c7e3e8cf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('cleaning', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_event_promoter_name'), 'event', ['promoter_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_promoter_name'), table_name='event')
    op.drop_column('event', 'cleaning')
    # ### end Alembic commands ###
