"""added update event link column to event table

Revision ID: eb401f8f1a7a
Revises: d7f7fbc9e276
Create Date: 2019-11-13 11:58:58.626912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb401f8f1a7a'
down_revision = 'd7f7fbc9e276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_event_date'), 'event', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_event_manager'), 'event', ['event_manager'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_other_notes'), 'event', ['other_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_other_notes'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_manager'), table_name='event')
    op.drop_index(op.f('ix_event_event_date'), table_name='event')
    # ### end Alembic commands ###
