"""added all remaining fields to event table 

Revision ID: fc105eaa97c3
Revises: 44cc83ece10d
Create Date: 2019-10-27 19:38:27.674206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc105eaa97c3'
down_revision = '44cc83ece10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('bar_min', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('booked', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('contract_sent', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('deposit_amount', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('deposit_paid', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('event_manager', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('event_type', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('guest_count', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('other_notes', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('tsl_approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_event_event_date'), 'event', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_event_manager'), 'event', ['event_manager'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_other_notes'), 'event', ['other_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_other_notes'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_manager'), table_name='event')
    op.drop_index(op.f('ix_event_event_date'), table_name='event')
    op.drop_column('event', 'tsl_approved')
    op.drop_column('event', 'other_notes')
    op.drop_column('event', 'guest_count')
    op.drop_column('event', 'event_type')
    op.drop_column('event', 'event_manager')
    op.drop_column('event', 'event_date')
    op.drop_column('event', 'deposit_paid')
    op.drop_column('event', 'deposit_amount')
    op.drop_column('event', 'contract_sent')
    op.drop_column('event', 'booked')
    op.drop_column('event', 'bar_min')
    # ### end Alembic commands ###
