"""events table

Revision ID: e7157ead5afa
Revises: c4b4f16a452a
Create Date: 2019-10-23 12:14:38.209748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7157ead5afa'
down_revision = 'c4b4f16a452a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'balance_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event', 'booked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event', 'cleaning',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event', 'contract_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event', 'deposit_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event', 'tsl_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'tsl_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event', 'deposit_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event', 'contract_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event', 'cleaning',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event', 'booked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event', 'balance_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
