"""events table

Revision ID: c4b4f16a452a
Revises: cfd475ea4121
Create Date: 2019-10-22 16:41:48.317733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b4f16a452a'
down_revision = 'cfd475ea4121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('promoter_name', sa.String(length=64), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('cleaning', sa.Boolean(), nullable=False),
    sa.Column('contract_sent', sa.Boolean(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.Column('deposit_paid', sa.Boolean(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('event_manager', sa.String(length=64), nullable=True),
    sa.Column('bar', sa.Boolean(), nullable=False),
    sa.Column('bar_min', sa.Integer(), nullable=False),
    sa.Column('tsl_approved', sa.Boolean(), nullable=False),
    sa.Column('balance_paid', sa.Boolean(), nullable=False),
    sa.Column('other_notes', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'deposit_amount', 'guest_count', 'bar_min')
    )
    op.create_index(op.f('ix_event_event_date'), 'event', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_event_manager'), 'event', ['event_manager'], unique=False)
    op.create_index(op.f('ix_event_event_name'), 'event', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_other_notes'), 'event', ['other_notes'], unique=False)
    op.create_index(op.f('ix_event_promoter_name'), 'event', ['promoter_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_promoter_name'), table_name='event')
    op.drop_index(op.f('ix_event_other_notes'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_event_manager'), table_name='event')
    op.drop_index(op.f('ix_event_event_date'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
